name: No Duplication beyond 4 lines only for c

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: Check duplications
      run: jscpd ./Rx/src/*.c --min-lines 4 --min-tokens 35 --threshold 0