name: UTBMSDataSender

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: build
      working-directory: ./Rx/tst/UT/UTReciever/
      run: gcc -Wall -Wextra -fprofile-arcs -ftest-coverage -o ./Rx/tst/UT/UTReciever/testchecker *.c
      
    - name: run
      run: ./testchecker

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: UTReciever_Coverage
        path: ./*.html
        retention-days: 1