name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Rx
        run: gcc -DMAIN -o Reciever  ./Rx/src/*.c
      - name : Sender | Reciever
        run: python ./GenerateSenderOutput.py | ./Reciever.exe
